### ISSUE TITLE
Typescript cannot find declaration file

### ISSUE THREAD

**Issue by mrmagic2020** [Basssiiie/OpenRCT2-Mocks#45]
**Describe the bug**
Typescript cannot find the declaration file:
```
Could not find a declaration file for module 'openrct2-mocks'. '/Users/.../node_modules/openrct2-mocks/dist/index.min.mjs' implicitly has an 'any' type.
  There are types at '/Users/.../node_modules/openrct2-mocks/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'openrct2-mocks' library may need to update its package.json or typings.
```

Console error logs:

```
Error: tests/currency.test.ts(4,18): error TS7016: Could not find a declaration file for module 'openrct2-mocks'. '/.../node_modules/openrct2-mocks/dist/index.min.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/openrct2-mocks` if it exists or add a new declaration (.d.ts) file containing `declare module 'openrct2-mocks';`
```

**To reproduce**
Steps to reproduce the behaviour:
1. `npm install openrct2-mocks --save-dev`.
2. In a typescript unit test, `import Mock from "openrct2-mocks"`.
3. See the warning message generated by vscode.
4. Run unit tests.
5. See console error.

**Expected behaviour**
Typescript modules can find the declaration file.

<img width="739" alt="image" src="https://github.com/Basssiiie/OpenRCT2-Mocks/assets/104749673/66e8b8c0-e94b-4295-807a-6375ab4b4705">

**Comment by Basssiiie** [comment]
Hey thank you for the issue. I wasn't expecting others to use this package, but it seems `exports.types` property is missing in the `package.json`. I recall reading that it would fallback to older properties in the package.json, but maybe they changed that in newer NPM versions. 😅
